### ISSUE TITLE
Fully document library with examples and verbose documentation

### ISSUE THREAD

**Issue by theflyingcodr** [libsv/go-spvchannels#21]
We have public comments on all methods but these could be improved with more detailed explanations and code examples, I find a handy tool to use when writing these is https://bradleyjkemp.dev/godoc-playground/ which lets you write and interact with go docs in real time.

A handy guide for writing godocs is https://elliotchance.medium.com/godoc-tips-tricks-cda6571549b and also https://go.dev/blog/godoc.

When this repo is published the docs will appear here https://pkg.go.dev/github.com/libsv/go-spvchannels so we want it to be as friendly to users as possible. Yep, we also need to update our other repos but lets make this one the example to follow.

**Comment by ctnguyen** [comment]
In the same PR, we should
 - Be able to publish  the package
 - Add install instruction in README
 - Add workflow status badge in README
